CI Update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -95,12 +95,44 @@ jobs:
         env:
           CI: 'Yes'
 
+      # - name: Run Unit Tests
+      #   working-directory: /home/runner/frappe-bench
+      #   run: |
+      #     pytest tests/
+      #     find frutter_cicd/frutter_cicd/doctype/ -name 'test_*.py' -exec pytest {} \;
       - name: Run Unit Tests
         working-directory: /home/runner/frappe-bench
         run: |
+          # Run pytest for all unit tests in the project
           pytest tests/
-          find frutter_cicd/frutter_cicd/doctype/ -name 'test_*.py' -exec pytest {} \;
 
+          # Find and run tests for all folders under frutter_cicd/frutter_cicd/doctype/
+          for folder in frutter_cicd/frutter_cicd/doctype/*/; do
+            if [[ -d "$folder" ]]; then
+              find "$folder" -name 'test_*.py' -exec pytest {} +
+            fi
+          done
+
+
+      # - name: Check for Test Cases
+      #   working-directory: /home/runner/frappe-bench
+      #   run: |
+      #     changed_files=$(git diff --name-only HEAD^ HEAD)
+      #     for file_name in $changed_files; do
+      #       if [[ $file_name == *.py ]]; then
+      #         base_name=$(basename $file_name .py)
+      #         test_file="test_${base_name}.py"
+      #         found_files=$(find . -name $test_file)
+      #         if [[ -n $found_files ]]; then
+      #           echo "Test file $test_file found."
+      #         else
+      #           echo "Test file $test_file not found."
+      #           exit 1
+      #         fi
+      #       fi
+      #     done
+      #   env:
+      #     CI: 'Yes'
       - name: Check for Test Cases
         working-directory: /home/runner/frappe-bench
         run: |
@@ -108,15 +140,20 @@ jobs:
           for file_name in $changed_files; do
             if [[ $file_name == *.py ]]; then
               base_name=$(basename $file_name .py)
-              test_file="test_${base_name}.py"
-              found_files=$(find . -name $test_file)
-              if [[ -n $found_files ]]; then
-                echo "Test file $test_file found."
+              if [[ $base_name == test_* ]]; then
+                echo "Test file $base_name.py found."
               else
-                echo "Test file $test_file not found."
-                exit 1
+                test_file="test_${base_name}.py"
+                found_files=$(find . -name $test_file)
+                if [[ -n $found_files ]]; then
+                  echo "Test file $test_file found."
+                else
+                  echo "Test file $test_file not found."
+                  exit 1
+                fi
               fi
             fi
           done
         env:
           CI: 'Yes'
+
