CI Update with test files

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,3 @@
-
 name: CI
 
 on:
@@ -58,7 +57,6 @@ jobs:
           restore-keys: |
             ${{ runner.os }}-pip-
             ${{ runner.os }}-
-
       - name: Get yarn cache directory path
         id: yarn-cache-dir-path
         run: 'echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT'
@@ -70,7 +68,6 @@ jobs:
           key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
           restore-keys: |
             ${{ runner.os }}-yarn-
-
       - name: Install MariaDB Client
         run: sudo apt-get install mariadb-client-10.6
 
@@ -80,7 +77,6 @@ jobs:
           bench init --skip-redis-config-generation --skip-assets --python "$(which python)" ~/frappe-bench
           mariadb --host 127.0.0.1 --port 3306 -u root -proot -e "SET GLOBAL character_set_server = 'utf8mb4'"
           mariadb --host 127.0.0.1 --port 3306 -u root -proot -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'"
-
       - name: Install
         working-directory: /home/runner/frappe-bench
         run: |
@@ -92,10 +88,28 @@ jobs:
         env:
           CI: 'Yes'
 
-      - name: Run Tests
+      - name: Run Unit Tests
         working-directory: /home/runner/frappe-bench
         run: |
-          bench --site test_site set-config allow_tests true
-          bench --site test_site run-tests --app frutter_cicd
+          pytest tests/
+          find frutter_cicd/frutter_cicd/doctype/ -name 'test_*.py' -exec pytest {} \;
+
+      - name: Check for Test Cases
+        working-directory: /home/runner/frappe-bench
+        run: |
+          changed_files=$(git diff --name-only HEAD^ HEAD)
+          for file_name in $changed_files; do
+            if [[ $file_name == *.py ]]; then
+              base_name=$(basename $file_name .py)
+              test_file="test_${base_name}.py"
+              found_files=$(find . -name $test_file)
+              if [[ -n $found_files ]]; then
+                echo "Test file $test_file found."
+              else
+                echo "Test file $test_file not found."
+                exit 1
+              fi
+            fi
+          done
         env:
-          TYPE: server
+          CI: 'Yes'
