Action check

diff --git a/.github/workflows/frutter_ci.yml b/.github/workflows/frutter_ci.yml
--- a/.github/workflows/frutter_ci.yml
+++ b/.github/workflows/frutter_ci.yml
@@ -37,15 +37,23 @@ jobs:
     - name: Check for test cases
       run: |
         # file_name=$(basename $GITHUB_WORKSPACE/$GITHUB_EVENT_NAME)
-        file_name=$(basename $GITHUB_WORKSPACE/$GITHUB_SHA)
-        test_file="${file_name//.py/_test.py}"
-        if [[ -f "tests/$test_file" || -f "frutter_cicd/frutter_cicd/doctype/$test_file" ]]; then
-          echo "Test file $test_file found."
-          pytest "tests/$test_file" "frutter_cicd/frutter_cicd/doctype/$test_file"
-        else
-          echo "Test file $test_file not found."
-          exit 1
-        fi
+        # Get the names of the files that were changed in the last commit
+        changed_files=$(git diff --name-only HEAD^ HEAD)
+
+        # Loop over each changed file
+        for file_name in $changed_files; do
+          # Remove the .py extension and add _test.py to get the test file name
+          test_file="${file_name//.py/_test.py}"
+
+          # Check if the test file exists in either the tests/ directory or the frutter_cicd/frutter_cicd/doctype/ directory
+          if [[ -f "tests/$test_file" || -f "frutter_cicd/frutter_cicd/doctype/$test_file" ]]; then
+            echo "Test file $test_file found."
+            pytest "tests/$test_file" "frutter_cicd/frutter_cicd/doctype/$test_file"
+          else
+            echo "Test file $test_file not found."
+            exit 1
+          fi
+        done
 
     - name: Merge develop into current branch
       run: git merge develop --no-commit --no-ff || echo "Conflict occurred"
